<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-JEV6767" name="com.cvs.qa.testcases.PhotoPageTest" tests="5" failures="1" timestamp="20 Jan 2019 16:36:56 GMT" time="47.601" errors="0">
  <testcase name="verifyPhotoPageTitleTest" time="10.270" classname="com.cvs.qa.testcases.PhotoPageTest">
    <skipped/>
  </testcase> <!-- verifyPhotoPageTitleTest -->
  <testcase name="verifyPhotoPageTitleTest" time="11.703" classname="com.cvs.qa.testcases.PhotoPageTest">
    <skipped/>
  </testcase> <!-- verifyPhotoPageTitleTest -->
  <testcase name="verifyPhotoPageTitleTest" time="8.056" classname="com.cvs.qa.testcases.PhotoPageTest">
    <skipped/>
  </testcase> <!-- verifyPhotoPageTitleTest -->
  <testcase name="verifyPhotoPageTitleTest" time="8.259" classname="com.cvs.qa.testcases.PhotoPageTest">
    <failure type="java.lang.AssertionError" message="expected [Photo Printing Services | Print Photos Online | CVS Photo] but found [CVS Photo: Photo Prints | Passport Photos | Photo Cards | Photo Books]">
      <![CDATA[java.lang.AssertionError: expected [Photo Printing Services | Print Photos Online | CVS Photo] but found [CVS Photo: Photo Prints | Passport Photos | Photo Cards | Photo Books]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.cvs.qa.testcases.PhotoPageTest.verifyPhotoPageTitleTest(PhotoPageTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyPhotoPageTitleTest -->
  <testcase name="verifyShopNowPicLinkTest" time="9.313" classname="com.cvs.qa.testcases.PhotoPageTest"/>
</testsuite> <!-- com.cvs.qa.testcases.PhotoPageTest -->
